#!/usr/bin/env python
"""
Script para crear manualmente la tabla core_datosfiscales
"""
import os
import django

# Configurar Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dental_saas.settings')
django.setup()

from django.db import connection

def main():
    cursor = connection.cursor()
    
    # Crear tabla core_datosfiscales
    sql = """
    CREATE TABLE IF NOT EXISTS core_datosfiscales (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        paciente_id BIGINT NOT NULL REFERENCES core_paciente(id) ON DELETE CASCADE,
        rfc VARCHAR(13) NOT NULL,
        razon_social VARCHAR(255) NOT NULL,
        domicilio_fiscal TEXT NOT NULL DEFAULT '',
        calle VARCHAR(150) NOT NULL DEFAULT '',
        numero_exterior VARCHAR(20) NOT NULL DEFAULT '',
        numero_interior VARCHAR(20) NOT NULL DEFAULT '',
        colonia VARCHAR(100) NOT NULL DEFAULT '',
        municipio VARCHAR(100) NOT NULL DEFAULT '',
        estado VARCHAR(100) NOT NULL DEFAULT '',
        codigo_postal VARCHAR(10) NOT NULL DEFAULT '',
        regimen_fiscal_id BIGINT NULL REFERENCES core_satregimenfiscal(id) ON DELETE SET NULL,
        uso_cfdi_id BIGINT NULL REFERENCES core_satusocfdi(id) ON DELETE SET NULL,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
    );
    """
    
    try:
        cursor.execute(sql)
        print("✅ Tabla core_datosfiscales creada exitosamente")
        
        # Verificar que se creó correctamente
        cursor.execute("SELECT COUNT(*) FROM core_datosfiscales;")
        count = cursor.fetchone()[0]
        print(f"✅ La tabla está accesible y tiene {count} registros")
        
    except Exception as e:
        print(f"❌ Error al crear tabla: {e}")

if __name__ == '__main__':
    main()
