# Generated by Django 5.2.4 on 2025-07-27 14:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('factura_adjunta', models.FileField(blank=True, null=True, upload_to='facturas_compras/', verbose_name='Factura (PDF/Imagen)')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color_hex', models.CharField(default='#FFFFFF', help_text='Color de fondo por defecto para este diagnóstico.', max_length=7)),
                ('icono_svg', models.TextField(blank=True, help_text='Código SVG del icono para superponer en el diente.')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=10, help_text='Nivel de stock para generar alertas.')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('apto_para_plan_de_pago', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o Razón Social')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion_fiscal', models.TextField(blank=True, verbose_name='Dirección Fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=255)),
                ('domicilio_fiscal', models.TextField()),
                ('uso_cfdi', models.CharField(default='Gastos en General', max_length=50)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_fiscales', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PRO', 'Programada'), ('CON', 'Confirmada'), ('ATN', 'Atendida (Pend. Pago)'), ('CAN', 'Cancelada'), ('COM', 'Completada')], default='PRO', max_length=3)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('requiere_factura', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=50)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.cita')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('especialidades', models.ManyToManyField(blank=True, to='core.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_dentista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('descripcion_evento', models.TextField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='core.paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfildentista')),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='core.perfildentista'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='core.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios_realizados',
            field=models.ManyToManyField(blank=True, to='core.servicio'),
        ),
        migrations.CreateModel(
            name='ServicioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='insumos',
            field=models.ManyToManyField(blank=True, through='core.ServicioInsumo', to='core.insumo'),
        ),
        migrations.CreateModel(
            name='EstadoDiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diente', models.IntegerField()),
                ('color_seleccionado', models.CharField(blank=True, help_text='Color personalizado para el fondo del diente (ej. resinas).', max_length=7)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.diagnostico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='core.paciente')),
            ],
            options={
                'unique_together': {('cliente', 'numero_diente')},
            },
        ),
    ]
