# Generated by Django 5.2.4 on 2025-07-27 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='requiere_lote_caducidad',
            field=models.BooleanField(default=False, help_text='Marcar si este insumo necesita seguimiento por lote y caducidad (COFEPRIS).'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Recibir'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Este campo se calcula automáticamente a partir de los lotes.'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=10, help_text='Nivel de stock global para generar alertas.'),
        ),
        migrations.CreateModel(
            name='LoteInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('numero_lote', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.insumo')),
                ('unidad_dental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_insumos', to='core.unidaddental')),
            ],
        ),
    ]
