# Generated by Django 5.2.4 on 2025-07-27 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unidaddental_insumo_requiere_lote_caducidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='unidad_dental',
            field=models.ForeignKey(blank=True, help_text='Unidad donde se realiza la cita.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidaddental'),
        ),
    ]
