# Generated by Django 5.2.4 on 2025-07-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cita_unidad_dental'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='registro_sanitario',
            field=models.CharField(blank=True, help_text='Registro COFEPRIS del insumo, si aplica.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_datos',
            field=models.BooleanField(default=False, help_text='El paciente ha aceptado el aviso de privacidad y tratamiento de datos.'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='firma_consentimiento',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_consentimiento/'),
        ),
        migrations.CreateModel(
            name='AvisoFuncionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_sanitario', models.CharField(max_length=255)),
                ('cedula_profesional', models.CharField(max_length=100)),
                ('fecha_presentacion', models.DateField()),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='cofepris/avisos/')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_funcionamiento', to='tenants.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('registro_sanitario', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_bpm', models.FileField(blank=True, null=True, upload_to='cofepris/equipos/', verbose_name='Certificado de Buenas Prácticas de Fabricación')),
                ('fecha_calibracion', models.DateField()),
                ('fecha_vencimiento_calibracion', models.DateField()),
                ('unidad_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.unidaddental')),
            ],
        ),
        migrations.CreateModel(
            name='Residuos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_recoleccion', models.CharField(help_text='Nombre de la empresa de recolección de RPBI.', max_length=255)),
                ('fecha_recoleccion', models.DateField()),
                ('manifiesto_pdf', models.FileField(upload_to='cofepris/residuos/')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones_residuos', to='tenants.clinica')),
                ('unidad_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones_residuos', to='core.unidaddental')),
            ],
        ),
    ]
