# Generated by Django 5.2.4 on 2025-07-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paciente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='consentimiento_datos',
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_cofepris',
            field=models.BooleanField(default=False, help_text='El paciente ha aceptado el aviso de privacidad y tratamiento de datos para COFEPRIS.'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PRO', 'Programada'), ('CON', 'Confirmada'), ('ATN', 'Atendida (Pend. Pago)'), ('CAN', 'Cancelada'), ('COM', 'Completada'), ('NSP', 'No se presentó')], default='PRO', max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apto_para_plan_de_pago',
            field=models.BooleanField(default=False, help_text='Indica si el dentista ha autorizado un plan de pagos para este paciente.'),
        ),
    ]
