# Generated by Django 5.2.4 on 2025-07-28 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_paciente_consentimiento_datos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto Corto'), ('TEXTAREA', 'Párrafo'), ('SI_NO', 'Sí / No'), ('MULTIPLE', 'Opción Múltiple')], default='SI_NO', max_length=10)),
                ('opciones', models.CharField(blank=True, help_text='Para opción múltiple, separar opciones con comas (ej. A,B,C)', max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_historial', to='core.paciente')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preguntahistorial')),
            ],
            options={
                'unique_together': {('paciente', 'pregunta')},
            },
        ),
    ]
