# Generated by Django 5.2.4 on 2025-07-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_preguntahistorial_respuestahistorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='saldo_pendiente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='saldo_global',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo total pendiente del paciente.', max_digits=10),
        ),
    ]
