# Generated by Django 5.2.4 on 2025-07-28 05:15

from django.db import migrations

def populate_paciente_from_cita(apps, schema_editor):
    Pago = apps.get_model('core', 'Pago')
    for pago in Pago.objects.all():
        if pago.cita:
            pago.paciente = pago.cita.cliente
            pago.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cita_saldo_pendiente_paciente_saldo_global'),
    ]

    operations = [
        migrations.RunPython(populate_paciente_from_cita, migrations.RunPython.noop),
    ]