# Generated by Django 5.2.4 on 2025-07-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_populate_pago_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='core.cita'),
        ),
    ]
