# Generated by Django 5.2.4 on 2025-07-28 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pago_paciente_alter_pago_cita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['especialidad', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='insumos',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios_planeados',
            field=models.ManyToManyField(blank=True, help_text='Servicios que se planea realizar', related_name='citas_planeadas', to='core.servicio'),
        ),
        migrations.AddField(
            model_name='compra',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_compra',
            field=models.CharField(choices=[('EXTERNA', 'Compra Externa'), ('INTERNA', 'Transferencia Interna'), ('AJUSTE', 'Ajuste de Inventario')], default='EXTERNA', max_length=10),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='especialidades_incluidas',
            field=models.ManyToManyField(blank=True, help_text='Especialidades cuyos servicios también puede realizar', to='core.especialidad'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30, help_text='Duración estimada en minutos'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.perfildentista'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PRO', 'Programada'), ('CON', 'Confirmada'), ('ATN', 'Atendida'), ('COM', 'Completada'), ('CAN', 'Cancelada')], default='PRO', max_length=3),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(blank=True, help_text='Síntomas específicos o notas adicionales', max_length=500),
        ),
        migrations.AlterField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicios_realizados',
            field=models.ManyToManyField(blank=True, help_text='Servicios que realmente se realizaron', related_name='citas_realizadas', to='core.servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='unidad_dental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.unidaddental'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='factura_adjunta',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Opcional para compras internas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='especialidad',
            field=models.ForeignKey(default=1, help_text='Especialidad requerida para realizar este servicio', on_delete=django.db.models.deletion.CASCADE, to='core.especialidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
