# Generated by Django 5.2.4 on 2025-07-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mejoras_citas_y_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio unitario del insumo.', max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Unidad de medida del insumo (ej. pieza, litro, kg).', max_length=50),
        ),
    ]
