# Generated by Django 5.2.4 on 2025-07-29 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_insumo_precio_unitario_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfiscales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='uso_cfdi',
            field=models.CharField(choices=[('G01', 'Adquisición de mercancías'), ('G03', 'Gastos en general'), ('I04', 'Equipo de computo y accesorios'), ('D01', 'Honorarios médicos, dentales y gastos hospitalarios.')], max_length=3),
        ),
    ]
