# Generated by Django 5.2.4 on 2025-07-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_datosfiscales_created_at_datosfiscales_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residuos',
            name='manifiesto_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cofepris/residuos/'),
        ),
        migrations.AlterField(
            model_name='residuos',
            name='proveedor_recoleccion',
            field=models.ForeignKey(blank=True, help_text='Empresa de recolección de RPBI. Puede dejarse en blanco si es un proveedor no registrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.perfildentista')),
            ],
            options={
                'ordering': ['dentista', 'dia_semana', 'hora_inicio'],
                'unique_together': {('dentista', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
