# Generated by Django 5.2.4 on 2025-08-19 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0015_fix_historialclinico_paciente_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del ícono (ej: fas fa-users)', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú')),
                ('activo', models.BooleanField(default=True)),
                ('url_pattern', models.CharField(blank=True, help_text='Patrón de URL para acceso directo', max_length=200)),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfildentista'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='unidad_dental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidaddental'),
        ),
        migrations.CreateModel(
            name='SubmenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('url_name', models.CharField(help_text='Nombre de la URL de Django (ej: core:paciente_list)', max_length=100)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del ícono', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_crear', models.BooleanField(default=False, help_text='¿Requiere permiso de creación?')),
                ('requiere_editar', models.BooleanField(default=False, help_text='¿Requiere permiso de edición?')),
                ('requiere_eliminar', models.BooleanField(default=False, help_text='¿Requiere permiso de eliminación?')),
                ('requiere_ver', models.BooleanField(default=True, help_text='¿Requiere permiso de visualización?')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='core.modulosistema')),
            ],
            options={
                'verbose_name': 'Elemento de Submenú',
                'verbose_name_plural': 'Elementos de Submenú',
                'ordering': ['modulo', 'orden', 'nombre'],
                'unique_together': {('modulo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submenu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submenuitem')),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Logs de Acceso',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acceso', models.CharField(choices=[('DENEGADO', 'Sin Acceso'), ('VER', 'Solo Ver'), ('CREAR', 'Ver y Crear'), ('EDITAR', 'Ver, Crear y Editar'), ('COMPLETO', 'Acceso Completo (CRUD)')], default='DENEGADO', max_length=10)),
                ('puede_ver', models.BooleanField(default=False)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('puede_exportar', models.BooleanField(default=False)),
                ('solo_propios_registros', models.BooleanField(default=False, help_text='¿Solo puede ver sus propios registros?')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_dinamicos', to='auth.group')),
                ('submenu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='core.submenuitem')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('rol', 'submenu_item')},
            },
        ),
    ]
