# Generated by Django 5.2.4 on 2025-08-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sincronizar_modelos_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacceso',
            name='accion_realizada',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='logacceso',
            name='detalles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logacceso',
            name='modulo_accedido',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
