# Generated by Django 5.2.4 on 2025-08-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_paciente_calle_paciente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildentista',
            name='cedula_profesional',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='perfildentista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='dentistas/fotos/'),
        ),
        migrations.AddField(
            model_name='perfildentista',
            name='titulo_profesional',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
