# Generated by Django 5.2.4 on 2025-08-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_perfildentista_cedula_profesional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildentista',
            name='cedula_profesional',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='dentistas/cedulas/'),
        ),
        migrations.AlterField(
            model_name='perfildentista',
            name='titulo_profesional',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='dentistas/titulos/'),
        ),
    ]
