# Generated by Django 5.2.4 on 2025-08-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_perfildentista_cedula_profesional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidaddental',
            name='dentistas_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Dentistas que pueden usar esta unidad', related_name='unidades_permitidas', to='core.perfildentista'),
        ),
    ]
