# Generated by Django 5.2.4 on 2025-08-23 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_unidaddental_dentistas_permitidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=10)),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CONCLUIDO', 'Concluido'), ('INCUMPLIDO', 'Incumplido')], default='ACTIVO', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_pago', to='core.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='core.paciente')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CuotaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_asignadas', to='core.pago')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='core.planpago')),
            ],
            options={
                'ordering': ['plan', 'numero'],
                'unique_together': {('plan', 'numero')},
            },
        ),
    ]
