# Generated by Django 5.2.4 on 2025-08-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_planpago_cuotaplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='forma_pago_sat',
            field=models.CharField(blank=True, help_text='SAT c_FormaPago, ej. 01, 03, 04, 28', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_sat',
            field=models.CharField(blank=True, help_text='SAT c_MetodoPago, ej. PUE o PPD', max_length=3, null=True),
        ),
    ]
