# Generated by Django 5.2.4 on 2025-08-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pago_forma_pago_sat_pago_metodo_sat'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfiscales',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='numero_exterior',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='numero_interior',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='domicilio_fiscal',
            field=models.TextField(blank=True, default=''),
        ),
    ]
