# Generated by Django 5.2.4 on 2025-09-16 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_satformapago_satmetodopago_satregimenfiscal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de ícono CSS (ej: fas fa-heart)', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal para la categoría', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Historial',
                'verbose_name_plural': 'Categorías de Historial',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='preguntahistorial',
            options={'ordering': ['categoria__orden', 'orden'], 'verbose_name': 'Pregunta de Historial', 'verbose_name_plural': 'Preguntas de Historial'},
        ),
        migrations.AlterModelOptions(
            name='respuestahistorial',
            options={'verbose_name': 'Respuesta de Historial', 'verbose_name_plural': 'Respuestas de Historial'},
        ),
        migrations.AddField(
            model_name='preguntahistorial',
            name='alerta_cofepris',
            field=models.BooleanField(default=False, help_text='Si requiere reporte a COFEPRIS'),
        ),
        migrations.AddField(
            model_name='preguntahistorial',
            name='importancia',
            field=models.CharField(choices=[('BAJA', 'Informativa'), ('MEDIA', 'Importante'), ('ALTA', 'Crítica'), ('CRITICA', 'Emergencia Médica')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='preguntahistorial',
            name='obligatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preguntahistorial',
            name='requiere_seguimiento',
            field=models.BooleanField(default=False, help_text='Si requiere seguimiento médico'),
        ),
        migrations.AddField(
            model_name='preguntahistorial',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Explicación adicional o contexto', max_length=300),
        ),
        migrations.AddField(
            model_name='respuestahistorial',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestahistorial',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestahistorial',
            name='notas_medicas',
            field=models.TextField(blank=True, help_text='Notas del dentista sobre esta respuesta'),
        ),
        migrations.AddField(
            model_name='respuestahistorial',
            name='requiere_atencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preguntahistorial',
            name='opciones',
            field=models.TextField(blank=True, help_text='Para opción múltiple, separar opciones con comas'),
        ),
        migrations.AlterField(
            model_name='preguntahistorial',
            name='texto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='preguntahistorial',
            name='tipo',
            field=models.CharField(choices=[('TEXT', 'Texto Corto'), ('TEXTAREA', 'Párrafo'), ('SI_NO', 'Sí / No'), ('MULTIPLE', 'Opción Múltiple'), ('FECHA', 'Fecha'), ('NUMERO', 'Número'), ('EMAIL', 'Email'), ('TELEFONO', 'Teléfono')], default='SI_NO', max_length=10),
        ),
        migrations.AddField(
            model_name='preguntahistorial',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.categoriahistorial'),
        ),
        migrations.CreateModel(
            name='CuestionarioCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('tiempo_completado_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('revision_medica', models.BooleanField(default=False, help_text='¿Ha sido revisado por el dentista?')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('notas_revision', models.TextField(blank=True)),
                ('tiene_alertas', models.BooleanField(default=False)),
                ('alertas_generadas', models.TextField(blank=True, help_text='Alertas automáticas generadas')),
                ('completado_por', models.ForeignKey(blank=True, help_text='Usuario que ayudó a completar el cuestionario (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios_completados', to='core.paciente')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuestionarios_revisados', to='core.perfildentista')),
            ],
            options={
                'verbose_name': 'Cuestionario Completado',
                'verbose_name_plural': 'Cuestionarios Completados',
                'ordering': ['-fecha_completado'],
            },
        ),
    ]
