# Generated by Django 5.2.4 on 2025-09-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cuestionario_historial_clinico'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: create_default_categoria_and_assign_preguntas(apps),
            reverse_code=migrations.RunPython.noop
        ),
    ]

def create_default_categoria_and_assign_preguntas(apps):
    """Crear categoría por defecto y asignar preguntas existentes"""
    CategoriaHistorial = apps.get_model('core', 'CategoriaHistorial')
    PreguntaHistorial = apps.get_model('core', 'PreguntaHistorial')
    
    # Crear categoría por defecto
    categoria_default, created = CategoriaHistorial.objects.get_or_create(
        nombre='General',
        defaults={
            'descripcion': 'Preguntas generales de historial clínico',
            'icono': 'fas fa-file-medical',
            'color': '#6c757d',
            'orden': 0,
            'activa': True
        }
    )
    
    # Asignar todas las preguntas sin categoría a la categoría por defecto
    preguntas_sin_categoria = PreguntaHistorial.objects.filter(categoria__isnull=True)
    for pregunta in preguntas_sin_categoria:
        pregunta.categoria = categoria_default
        pregunta.save()
