# Generated by Django 5.2.4 on 2025-10-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_prepare_clinical_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historialestadodiente',
            new_name='core_histor_pacient_73bcb1_idx',
            old_name='core_histor_pacient_a8e7c7_idx',
        ),
        migrations.RenameIndex(
            model_name='historialestadodiente',
            new_name='core_histor_fecha_c_93a897_idx',
            old_name='core_histor_fecha_c_4e3b83_idx',
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='registrado_por',
            field=models.ForeignKey(help_text='Dentista o personal que registra la entrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfildentista'),
        ),
    ]
