# Generated by Django 5.2.4 on 2025-10-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_core_histor_pacient_a8e7c7_idx_core_histor_pacient_73bcb1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servicios_realizados',
        ),
    ]
