# Generated by Django 5.2.4 on 2025-10-23 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_eliminar_servicios_realizados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AJUSTE_MANUAL', 'Ajuste Manual'), ('ENTRADA_COMPRA', 'Entrada por Compra'), ('SALIDA_CONSUMO', 'Salida por Consumo'), ('TRANSFERENCIA', 'Transferencia entre Unidades'), ('MERMA', 'Merma/Vencimiento'), ('CORRECCION', 'Corrección de Error')], max_length=20)),
                ('motivo', models.CharField(choices=[('CONTEO_FISICO', 'Conteo Físico'), ('VENCIMIENTO', 'Producto Vencido'), ('MERMA', 'Merma/Desperdicio'), ('ERROR_REGISTRO', 'Error en Registro Anterior'), ('TRANSFERENCIA', 'Transferencia entre Unidades'), ('CONSUMO_TRATAMIENTO', 'Consumo en Tratamiento'), ('OTRO', 'Otro Motivo')], max_length=30)),
                ('cantidad_anterior', models.IntegerField(help_text='Cantidad antes del movimiento')),
                ('cantidad_nueva', models.IntegerField(help_text='Cantidad después del movimiento')),
                ('diferencia', models.IntegerField(help_text='Diferencia (+/-)')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.loteinsumo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
