# Generated by Django 5.2.4 on 2025-10-24 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_agregar_movimiento_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('costo_referencia', models.DecimalField(decimal_places=2, help_text='Costo de referencia por unidad', max_digits=8)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Trabajo de Laboratorio',
                'verbose_name_plural': 'Tipos de Trabajos de Laboratorio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dientes', models.CharField(help_text='Números de dientes (ej: 11,12,13)', max_length=100)),
                ('material', models.CharField(blank=True, help_text='Material (Zirconia, Porcelana, etc.)', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Color/tono (ej: A2)', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Indicaciones especiales')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(help_text='Fecha estimada de entrega')),
                ('fecha_entrega_real', models.DateField(blank=True, help_text='Fecha real de entrega del laboratorio', null=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO', 'Entregado'), ('COLOCADO', 'Colocado en Paciente'), ('PAGADO', 'Pagado a Laboratorio'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('costo_laboratorio', models.DecimalField(decimal_places=2, help_text='Costo cobrado por el laboratorio', max_digits=8)),
                ('precio_paciente', models.DecimalField(decimal_places=2, help_text='Precio cobrado al paciente', max_digits=8)),
                ('notas', models.TextField(blank=True)),
                ('cita_origen', models.ForeignKey(help_text='Cita donde se solicitó el trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_laboratorio', to='core.cita')),
                ('dentista_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_solicitados', to='core.perfildentista')),
                ('laboratorio', models.ForeignKey(help_text='Técnico dental o laboratorio', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_laboratorio', to='core.proveedor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_laboratorio', to='core.paciente')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='core.tipotrabajolaboratorio')),
            ],
            options={
                'verbose_name': 'Trabajo de Laboratorio',
                'verbose_name_plural': 'Trabajos de Laboratorio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
