# Generated by Django 5.2.4 on 2025-10-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_tipotrabajolaboratorio_trabajolaboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajolaboratorio',
            name='cita_origen',
            field=models.ForeignKey(blank=True, help_text='Cita donde se solicitó el trabajo (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_laboratorio', to='core.cita'),
        ),
    ]
