# Generated by Django 5.2.4 on 2025-10-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_trabajolaboratorio_cita_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_por_empaque',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de unidades individuales por empaque (ej. 100 guantes por caja).'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_empaque',
            field=models.CharField(blank=True, help_text='Tipo de empaque (ej. Caja, Paquete, Bulto). Dejar vacío si se compra por unidad individual.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del insumo (opcional para compras en tiendas como Garis, Walmart, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, default='pieza', help_text='Unidad de medida individual (ej. pieza, litro, kg).', max_length=50),
        ),
    ]
