# Generated by Django 5.2.4 on 2025-10-28 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_insumo_cantidad_por_empaque_insumo_unidad_empaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='costos_capturados',
            field=models.BooleanField(default=False, help_text='Indica si ya se capturaron los costos de esta compra'),
        ),
        migrations.AddField(
            model_name='loteinsumo',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Costo de entrada desde la compra. Se captura cuando llega la factura.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loteinsumo',
            name='detalle_compra',
            field=models.ForeignKey(blank=True, help_text='Referencia al detalle de compra que originó este lote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_generados', to='core.detallecompra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Se calcula al capturar los costos de la factura', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Se captura cuando llega la factura del proveedor', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Precio de referencia (opcional). El costo real se captura en cada compra.', max_digits=10, null=True),
        ),
    ]
