# Generated by Django 5.2.4 on 2025-10-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_separar_inventario_y_costos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cambio_devuelto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cambio devuelto al cliente', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto en efectivo recibido del cliente (solo para pagos en efectivo)', max_digits=10, null=True),
        ),
    ]
