# Generated by Django 5.2.4 on 2025-10-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_agregar_campos_cambio_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True),
        ),
    ]
