# Generated by Django 5.2.4 on 2025-07-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_clinica_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='documento_consentimiento',
            field=models.FileField(blank=True, help_text='PDF con el aviso de privacidad y consentimiento de COFEPRIS.', null=True, upload_to='consentimientos/'),
        ),
    ]
